language: node_js

node_js:
  - '8'

script:
  - yarn test
  - yarn build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/Offline_Manga_Reader.user.js
  skip_cleanup: true
  on:
    tags: true
